### ISSUE TITLE
typescript support?

### ISSUE THREAD

**Issue by jasonfharris** [kartikk221/hyper-express-session#2]
Hey there,

Thanks for hyper-express! I was wondering if you could add typescript support for this module?

Thanks!
   Jason

**Comment by kartikk221** [comment]
Hi, types are being added to this middleware at the moment and should be released soon.

**Comment by jasonfharris** [comment]
Thanks!

**Comment by kartikk221** [comment]
Hi, TypeScript types have been added in v1.1.0.

**Comment by jasonfharris** [comment]
Brilliant! Thanks!!
