### ISSUE TITLE
request.session.signed_id in undefined

### ISSUE THREAD

**Issue by caracal7** [kartikk221/hyper-express-session#4]
```javascript
Server.get('/auth/login', async (request, response) => {

    await request.session.start();

    await request.session.set({
        myid: 'some_id',
        visits: 0,
    });

    console.log('request.session.id', request.session.id)
    console.log('request.session.signed_id', request.session.signed_id) // <-------------- undefined

    return response.json({
        token: request.session.signed_id
    });
});
```
Ubuntu / Node 18.1.0

P.S. At local machine (OSX) everything is working and "signed_id" is present

**Comment by kartikk221** [comment]
Hey, so I added the above code to the HyperExpress tests for the Session middleware [here](https://github.com/kartikk221/hyper-express/blob/master/tests/middlewares/hyper-express-session/scenarios/properties.js) and I was unable to re-create the behavior where "signed_id" is undefined after `session.start()` method has been properly called and awaited.

Would you be able to follow these [steps](https://github.com/kartikk221/hyper-express#testing-changes) and test HyperExpress on your Ubuntu / Node 18.1.0 environment to see If you can potentially detect a failing test?

**Comment by caracal7** [comment]
@kartikk221 Thank you for such a quick response and for a great server.

This is not a HyperExpress problem. Seems like my code is not uploaded correctly. Everything is working perfect and all tests passed.👍

My fault. Sorry

**Comment by kartikk221** [comment]
No problem at all! Glad your issue got resolved.
