### ISSUE TITLE
Better typescript support?

### ISSUE THREAD

**Issue by ImLunaHey** [kartikk221/hyper-express-session#6]
Thanks for the initial Typescript support. 💖 
Just tried one of the examples and my IDE isn't liking it. 😞 

![image](https://user-images.githubusercontent.com/105922175/174572310-ae46a591-7e6b-417d-8f02-ce5e04e836d3.png)

This is from `webserver.use(sessionStore);`

I also get an issue with `request.session` not being typed.
![image](https://user-images.githubusercontent.com/105922175/174572623-a0e84eb8-3274-4cb9-b4a6-adb14eb00e9a.png)

**Comment by ImLunaHey** [comment]
Something like this might be needed.

```ts
import Session from 'hyper-express-session/types/components/Session';
import SessionEngine from 'hyper-express-session';
declare module 'hyper-express' {
    interface Request {
        session: Session
    }

    interface Router {
        use(sessionEngine: SessionEngine): void;
        use(pattern: string, sessionEngine: SessionEngine): void;
    }
}
```

**Comment by kartikk221** [comment]
Hello, I believe the reason why it is throwing problems is because RequestDefaultLocals is meant to allow for local properties to be attached to Request. You can try casting the request.session property as the Session type which should be exported by hyper-express-session. If that doesn't fully resolve the issue, feel free to make a Pull Request and I'd be glad to merge any solutions.

**Comment by ImLunaHey** [comment]
> Hello, I believe the reason why it is throwing problems is because RequestDefaultLocals is meant to allow for local properties to be attached to Request. You can try casting the request.session property as the Session type which should be exported by hyper-express-session. If that doesn't fully resolve the issue, feel free to make a Pull Request and I'd be glad to merge any solutions.

I've included the changes needed in the comment above yours. Casting is not the correct way todo this.

**Comment by ImLunaHey** [comment]
The changes I provided above work. 🥳 

![image](https://user-images.githubusercontent.com/105922175/174675629-fb1dc29e-0504-4647-a586-82ebf70b92e0.png)

**Comment by kartikk221** [comment]
I'm not too familiar with declaring modules in TypeScript. Would you be able to make a Pull Request with your TypeScript changes above, I'd be glad to merge them to allow for this to work? I'm assuming you would be adding the module declaration in the index.d.ts for the types of hyper-express-session?

**Comment by ImLunaHey** [comment]
Give me a bit more time and I'll do that. 😄 

Looks like I should be able to make the session fully typed.
